services:
  - type: web
    name: zaffy-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: HF_API_KEY
        sync: false
